import React from "react";
import {AbsoluteFill, Audio, Composition, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig, registerRoot} from "remotion";

const BLUE="#0879E8", NAVY="#07121F", OFF="#F7F8FA", INK="#08182A", PALE="#EEF2FF";
const FONT="Arial, Helvetica, sans-serif";
const LogoMark=({size=62}:{size?:number})=><div style={{width:size,height:size,borderRadius:size*.29,background:BLUE,position:"relative",overflow:"hidden",flex:"0 0 auto"}}><div style={{position:"absolute",width:size*.48,height:size*.16,borderRadius:20,background:"#fff",left:size*.19,top:size*.43,transform:"rotate(-45deg)"}}/><div style={{position:"absolute",width:size*.31,height:size*.16,borderRadius:20,background:"#fff",left:size*.49,top:size*.34,transform:"rotate(45deg)"}}/></div>;
const Txt=({children,size=64,weight=600,color=INK,style={}})=> <div style={{fontFamily:FONT,fontSize:size,fontWeight:weight,color,lineHeight:1.02,letterSpacing:-2,...style}}>{children}</div>;
const Scene=({children,bg})=><AbsoluteFill style={{background:bg}}>{children}</AbsoluteFill>;
const Pop=({children,delay=0,style={}})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const s=spring({frame:Math.max(0,f-delay),fps,config:{damping:15,stiffness:180,mass:.7}});return <div style={{transform:`translateY(${interpolate(s,[0,1],[22,0])}px) scale(${interpolate(s,[0,1],[.92,1])})`,opacity:s,...style}}>{children}</div>};
const Float=({children,amp=10,speed=1.8,style={}})=>{const f=useCurrentFrame();const y=Math.sin(f/(30*speed))*amp;return <div style={{transform:`translateY(${y}px)`,...style}}>{children}</div>};
const Phone=({detailed=false})=>{const f=useCurrentFrame();return <div style={{width:detailed?360:250,height:detailed?680:500,borderRadius:48,border:`5px solid ${detailed?INK:"#DCE5F0"}`,background:detailed?"#fff":"rgba(255,255,255,.025)",boxShadow:detailed?"0 24px 60px rgba(8,24,42,.12)":"none",position:"relative",padding:24,boxSizing:"border-box",transform:detailed?`rotate(${Math.sin(f/25)*.7}deg)`:undefined}}><div style={{width:90,height:9,borderRadius:9,background:detailed?INK:"#6C7B8D",opacity:.65,margin:"0 auto 34px"}}/>{[72,54,82,42,68].map((w,i)=><div key={i} style={{height:12,borderRadius:8,background:i===2?BLUE:(detailed?"#D9DEE7":"#637487"),opacity:detailed?1:.7,width:`${w}%`,marginTop:28,transform:`translateX(${Math.sin((f+i*13)/18)*3}px)`}}/>)}{detailed&&<div style={{position:"absolute",left:24,right:24,bottom:28,display:"flex",gap:10}}><div style={{height:42,flex:1,borderRadius:12,background:"#EEF1F5"}}/><div style={{height:42,width:42,borderRadius:12,background:"#DDE3EA"}}/></div>}</div>};
const MessageCard=({delay=0})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const s=spring({frame:Math.max(0,f-delay),fps,config:{damping:13,stiffness:150,mass:.65}});return <div style={{position:"absolute",width:420,background:"#fff",borderRadius:22,padding:24,boxShadow:"0 20px 45px rgba(8,24,42,.15)",transform:`translateX(${interpolate(s,[0,1],[180,0])}px) translateY(${interpolate(s,[0,.72,1],[0,-14,0])}px)`,opacity:s,zIndex:4}}><div style={{display:"flex",alignItems:"center",gap:14}}><div style={{width:46,height:46,borderRadius:14,background:"#18A77B",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",fontWeight:800,fontSize:20}}>✦</div><div><div style={{fontFamily:FONT,fontWeight:750,fontSize:20,color:INK}}>Verify</div><div style={{fontFamily:FONT,fontSize:14,color:"#7B8794"}}>Today · 10:42</div></div></div><div style={{fontFamily:FONT,fontSize:17,color:"#596574",marginTop:18}}>Your verification code is</div><div style={{fontFamily:FONT,fontSize:38,fontWeight:800,color:INK,letterSpacing:6,marginTop:5}}>482 913</div><div style={{height:10,width:"70%",background:"#E7EBF0",borderRadius:6,marginTop:20}}/></div>};

export const MainVideo=()=>{const f=useCurrentFrame(),F=(s:number)=>Math.round(s*30);return <AbsoluteFill style={{fontFamily:FONT}}><Audio src={staticFile("assets/background.mp3")} volume={1}/>

{f<F(3)&&<Scene bg={BLUE}><div style={{display:"flex",height:"100%",alignItems:"center",padding:"0 90px",gap:70}}><div style={{width:"50%"}}><Pop><Txt size={84} weight={500} color="#fff">Bots are</Txt></Pop><Pop delay={7}><Txt size={96} weight={850} color="#fff">getting<span style={{fontWeight:400}}>…</span></Txt></Pop><Float amp={6} speed={1.2} style={{marginTop:25}}><div style={{fontFamily:FONT,fontSize:22,fontWeight:650,color:"rgba(255,255,255,.75)"}}>Messages keep coming.</div></Float></div><div style={{position:"relative",width:540,height:500}}><Pop delay={3} style={{position:"absolute",right:30,top:25,width:390,background:"#fff",borderRadius:22,padding:22,boxShadow:"0 18px 50px rgba(0,0,0,.18)"}}><div style={{fontWeight:800,color:INK,fontSize:20}}>New message</div><div style={{height:12,width:"75%",background:"#DDE4EC",borderRadius:8,marginTop:16}}/></Pop><Pop delay={12} style={{position:"absolute",right:0,top:165,width:330,background:"#EAF3FF",borderRadius:20,padding:18}}><div style={{fontWeight:700,color:INK,fontSize:17}}>+1 202 ••• ••91</div><div style={{height:10,width:"80%",background:"#B8D5F4",borderRadius:8,marginTop:12}}/></Pop><Pop delay={24} style={{position:"absolute",right:90,top:305,width:290,background:"#fff",borderRadius:20,padding:18}}><div style={{fontWeight:700,color:INK,fontSize:16}}>Notification</div><div style={{height:10,width:"60%",background:"#DDE4EC",borderRadius:8,marginTop:12}}/></Pop></div></div></Scene>}

{f>=F(3)&&f<F(6)&&<Scene bg={NAVY}><div style={{height:"100%",display:"flex",alignItems:"center",justifyContent:"center",position:"relative"}}><Float amp={9}><Phone/></Float><div style={{position:"absolute",fontFamily:FONT,fontSize:108,fontWeight:800,color:"#fff",opacity:.82,transform:`translateY(${Math.sin(f/9)*7}px) scale(${interpolate(f,[90,104],[.92,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})})`}}>Fake users?</div><div style={{position:"absolute",bottom:70,fontFamily:FONT,fontSize:18,color:"#718092",letterSpacing:3}}>SIGNAL / NOISE / TRUST</div></div></Scene>}

{f>=F(6)&&f<F(8)&&<Scene bg={OFF}><div style={{height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><Float amp={8}><LogoMark size={58}/></Float></div></Scene>}

{f>=F(8)&&f<F(11)&&<Scene bg={OFF}><div style={{height:"100%",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{textAlign:"center",transform:`translateY(${Math.sin(f/14)*5}px)`}}><Txt size={70} weight={450} color="#AEB6C1">Verify</Txt><Txt size={78} weight={850} color={INK}>humans across any channel</Txt><div style={{width:`${interpolate(f,[240,300],[12,100],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}%`,height:5,background:BLUE,borderRadius:5,margin:"28px auto 0"}}/></div></div></Scene>}

{f>=F(11)&&f<F(15)&&<Scene bg={PALE}><div style={{height:"100%",display:"flex",alignItems:"center",justifyContent:"center",gap:55,position:"relative"}}><Float amp={5}><Phone detailed/></Float><div style={{position:"relative",width:520,height:600,marginLeft:-125}}><MessageCard delay={3}/><div style={{position:"absolute",bottom:45,left:20,width:360}}>{[70,52,85].map((w,i)=><div key={i} style={{height:14,width:`${w}%`,background:i===1?BLUE:"#D6DCE5",borderRadius:8,marginTop:18,transform:`translateX(${Math.sin((f+i*10)/13)*5}px)`}}/>)}</div></div></div></Scene>}

{f>=F(15)&&f<F(18)&&<Scene bg={OFF}><div style={{height:"100%",display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column"}}><div style={{transform:`scale(${interpolate(f,[450,462],[.84,1],{extrapolateRight:"clamp"})}) translateY(${Math.sin(f/7)*4}px)`}}><Txt size={112} weight={900}>Deny fakes</Txt></div><div style={{marginTop:28,width:190,height:4,background:BLUE,borderRadius:4,transform:`scaleX(${interpolate(f,[462,510],[.2,1],{extrapolateRight:"clamp"})})`}}/></div></Scene>}

{f>=F(18)&&<Scene bg={OFF}><div style={{height:"100%",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><Float amp={5}><div style={{display:"flex",alignItems:"center",gap:18}}><LogoMark size={62}/><Txt size={76} weight={850}>BRAND</Txt></div></Float><div style={{marginTop:52,height:70,border:"2px solid #A9B3BF",borderRadius:38,padding:"0 30px",display:"flex",alignItems:"center",fontFamily:FONT,fontSize:25,fontWeight:600,color:INK,overflow:"hidden",whiteSpace:"nowrap",maxWidth:`${f<F(20)?650:920}px`,transition:"none"}}><span>Think your system can spot fakes?</span>{f>=F(20)&&<span style={{marginLeft:18,fontWeight:850,color:BLUE}}>Prove it</span>}</div></div></Scene>}
</AbsoluteFill>};

registerRoot(()=> <Composition id="MainVideo" component={MainVideo} durationInFrames={660} fps={30} width={1920} height={1080}/>);